name: Test Workflow Listener

on:
  pull_request_target:
    types: [labeled]
    branches:
      - main

jobs:
  on-label:
    permissions:
      actions: read
      checks: write
      pull-requests: write
    uses: ./.github/workflows/build-test-lint-simple.yml
    secrets: inherit
    if: ${{ github.event.label.name == 'ready-to-test' || github.event.label.name == 'skip-tests' }}
